-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 09/07/2013 08:43:17
-- Server version: 5.1.53-community
-- Client version: 4.1

USE basedatos;

DELIMITER $$

DROP PROCEDURE IF EXISTS spRepVencidos$$
CREATE DEFINER = 'billetimax'@'%'
PROCEDURE spRepVencidos (IN FechaIni date, IN FechaFin date, IN DiasEnajena integer, IN TipoContrato integer, IN TipoPrenda integer)
BEGIN
  SELECT DISTINCT
    e.ID,
    e.NumContrato,
    e.Fecha,
    e.Vencimiento,
    CONCAT(c.Nombre, ' ', c.Apellido) AS Cliente,
    c.Tel,
    c.Celular,
    e.Avaluo,
    e.Serie,
    e.Prestamo,
    e.TipoInteres,
    e.TipoTasa
  FROM empeno e
    INNER JOIN clientes c
      ON e.IDCliente = c.ID
    LEFT JOIN detallesempeno de
      ON e.ID = de.IDEmpeno
  WHERE IF(TipoContrato = 1, (e.Serie = 1 OR e.Serie = 2 OR e.Serie = 3), IF(TipoContrato = 3, e.Serie = 2, de.Tipo = TipoPrenda)) AND DATE_FORMAT(ADDDATE(e.Vencimiento, INTERVAL IF(e.TipoTasa = 'DIARIA', 0, DiasEnajena) DAY), '%Y%/%m%/%d') BETWEEN FechaIni AND FechaFin AND e.Cancelado = 0 AND e.Destino = 0 AND e.Pagado = 0
  ORDER BY NumContrato;
END
$$

DELIMITER ;